var products = [
	{
		"name": "ägg",
		"eko": false,
		"price": 35.95,
		"category": "eggs"
	},
	{
		"name": "ägg",
		"eko": true,
		"price": 39.95,
		"category": "eggs"
	},
	{
		"name": "mjölk",
		"eko": false,
		"price": 10,
		"category": "milk"
	},
	{
		"name": "mjölk",
		"eko": true,
		"price": 12,
		"category": "milk"
	},
	{
		"name": "lamm",
		"eko": false,
		"price": 40,
		"category": "meat"
	},
	{
		"name": "lamm",
		"eko": true,
		"price": 50,
		"category": "meat"
	},
	
]